version: "3.0"
services:
  db:
    container_name: "database"
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "5434:5432"
    restart: always