"""empty message

Revision ID: f7e920b348fb
Revises: 190ba0fdfec6
Create Date: 2025-01-30 15:09:44.454197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e920b348fb'
down_revision: Union[str, None] = '190ba0fdfec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('executor', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'executor')
    # ### end Alembic commands ###
